### ISSUE TITLE
Name tag for cross-country tracks

### ISSUE THREAD

**Issue by dcesari** [russellporter/openskimap.org#121] opened 2024-03-05 09:56 UTC
When checking the rendering on openskimap of cross-country ski tracks I edited, I noticed that ski track relations, which I interpret as being monolithic units from the point of view of a skier, may get split into segments if the segments composing the relation (typically gravel roads) have a name tag (likely not related to its use as a ski track) different from the name indicated in the piste relation.

Taking as an example the black track which appears in https://openskimap.org/#13.57/46.36744/11.42069 , it is a single relation with the following tags:

name Kosertal
piste:type nordic
route piste
type route

however on openskimap it is actually split into 3 segments with different names. Is this behaviour desired? Are there any suggestions, apart from deleting the name tag from the segments, which I would like to avoid, for rendering relations as a single segment?

Possibly related to #114

**Comment by russellporter** [comment] 2024-03-05 21:24
> may get split into segments if the segments composing the relation (typically gravel roads) have a name tag (likely not related to its use as a ski track) different from the name indicated in the piste relation.

That's intended behavior, it's not really possible to know the intentions in the example linked. It could also be that there is a way with the piste name and a longer distance ski route that uses it.

To disambiguate the data, I'd suggest adding a `piste:name=Kosertal` tag to the ways. This will override the `name` tag. If both the route and the way have the same name, they are merged. Then the segments should be merged, unless there is some other difference like grooming or difficulty for example.

It would also be useful to have functionality to view the routes as defined in OSM - this is tracked by #80

**Closed by russellporter** 2024-03-05 21:24 UTC

**Comment by dcesari** [comment] 2024-03-06 07:40
Thank you for the suggestion
